version: '3.7'
services:
  app:
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
volumes:
  bundle_data:
    driver: local
